title: project-name Documentation
description: > 
  project-description

author: weijd
email: your-email@example.com
twitter_username: your-twitter-username
github_username: MangoMaster

theme: jekyll-theme-cayman

plugins:
  - jekyll-feed
  - jekyll-sitemap