title: project-name Documentation
author: weijd
# email: your-email@domain.com
description: > 
  Documentation for project-name

# social links
# twitter_username: your-twitter-handle
github_username:  MangoMaster

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-cayman